=== Koko2034/lm/EjerciciosClaseLM/examen/trenes.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT trenes ((getInformacionTrenesReturn))>
	<!ELEMENT getInformacionTrenesReturn ((infoTrenIda+, infoTrenVuelta+))>

	<!ELEMENT infoTrenIda ((tren, tipoTren, horaSalida, horaLlegada, origen, destino, clases+, infoAdicionales?))>
	<!ELEMENT infoTrenVuelta ((tren, tipoTren, horaSalida, horaLlegada, origen, destino, clases+, infoAdicionale?))>
		
		<!ELEMENT tren (#PCDATA)>
		<!ELEMENT tipoTren ((cdgoTipoTren, descTipoTren))>
			<!ELEMENT cdgoTipoTren (#PCDATA) REQUIRED>
			<!ELEMENT descTipoTren (#PCDATA) REQUIRED>
		<!ELEMENT horaSalida (#PCDATA)>
		<!ELEMENT horaLlegada (#PCDATA)>
		<!ELEMENT origen ((cdgoEstacion, descEstacion))>
		<!ELEMENT destino ((cdgoEstacion, descEstacion))>
			<!ELEMENT cdgoEstacion (#PCDATA) REQUIRED>
			<!ELEMENT descEstacion (#PCDATA) REQUIRED>
		<!ELEMENT clases ((cdgoClase, descClase, ocupaciones))+>
			<!ELEMENT cdgoClase (#PCDATA)>
			<!ELEMENT descClase (#PCDATA)>
			<!ELEMENT ocupaciones ((cdgoOcupacion, descOcupacion, tarifas*))>
				<!ELEMENT cdgoOcupacion (#PCDATA)>
				<!ELEMENT descOcupacion (#PCDATA)>
					<!ELEMENT tarifas ((cdgoTarifa, descTarifa, disponibilidad, precio, claseComercial))>
						<!ELEMENT cdgoTarifa (#PCDATA)>
						<!ELEMENT descTarifa (#PCDATA)>
						<!ELEMENT disponibilidad (#PCDATA)>
						<!ELEMENT precio (#PCDATA)>
						<!ELEMENT claseComercial EMPTY>
		<!ELEMENT infoAdicionales ((cdgoInformacion, txtoInformacion))*>
			<!ELEMENT cdgoInformacion (#PCDATA)>			
			<!ELEMENT txtoInformacion (#PCDATA)>

=== Koko2034/lm/EjerciciosClaseLM/examen/trenesMal.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE trenes SYSTEM "trenes.dtd">
<trenes>
	<getInformacionTrenesReturn>
		<infoTrenIda>
			<tren>02063</tren>
			<tipoTren>
				<cdgoTipoTren>006</cdgoTipoTren>
				<descTipoTren>AVE</descTipoTren>
			</tipoTren>
			<horaSalida>0620</horaSalida>
			<horaLlegada>0905</horaLlegada>
			<origen>
				<cdgoEstacion>54413</cdgoEstacion>
				<descEstacion>MALAGA M.Z</descEstacion>
			</origen>
			<destino>
				<cdgoEstacion>60000</cdgoEstacion>
				<descEstacion>MADRID-P.A</descEstacion>
			</destino>
			<clases>
				<cdgoClase>T</cdgoClase>
				<descClase>Turista</descClase>
				<ocupaciones>
					<cdgoOcupacion>CR</cdgoOcupacion>
					<descOcupacion>Sentada</descOcupacion>
					<tarifas>
						<cdgoTarifa>GL011</cdgoTarifa>
						<descTarifa>Nino</descTarifa>
						<disponibilidad>Si</disponibilidad>
						<precio>4770</precio>
						<claseComercial/>
					</tarifas>
					<tarifas>
						<cdgoTarifa>GL013</cdgoTarifa>
						<descTarifa>Tfa. Tarjeta Dorada</descTarifa>
						<disponibilidad>Si</disponibilidad>
						<precio>4770</precio>
						<claseComercial/>
					</tarifas>
					<tarifas>
						<cdgoTarifa>GL030</cdgoTarifa>
						<descTarifa>C. Joven &lt; 26</descTarifa>
						<disponibilidad>Si</disponibilidad>
						<precio>6360</precio>
						<claseComercial/>
					</tarifas>
					<tarifas>
						<cdgoTarifa>GL115</cdgoTarifa>
						<descTarifa>IDA Y VUELTA</descTarifa>
						<disponibilidad>Si</disponibilidad>
						<precio>6360</precio>
						<claseComercial/>
					</tarifas>
					<tarifas>
						<cdgoTarifa>GL010</cdgoTarifa>
						<descTarifa>FLEXIBLE</descTarifa>
						<disponibilidad>Si</disponibilidad>
						<precio>7950</precio>
						<claseComercial/>
					</tarifas>
				</ocupaciones>
			</clases>
			<clases>
				<cdgoClase>P</cdgoClase>
				<descClase>Turista Plus</descClase>
				<ocupaciones>
					<cdgoOcupacion>CR</cdgoOcupacion>
					<descOcupacion>Sentada</descOcupacion>
					<tarifas>
						<cdgoTarifa>GL011</cdgoTarifa>
						<descTarifa>Nino</descTarifa>
						<disponibilidad>Si</disponibilidad>
						<precio>5725</precio>
						<claseComercial/>
					</tarifas>
					<tarifas>
						<cdgoTarifa>GL013</cdgoTarifa>
						<descTarifa>Tfa. Tarjeta Dorada</descTarifa>
						<disponibilidad>Si</disponibilidad>
						<precio>5725</precio>
						<claseComercial/>
					</tarifas>
					<tarifas>
						<cdgoTarifa>GL030</cdgoTarifa>
						<descTarifa>C. Joven &lt; 26</descTarifa>
						<disponibilidad>Si</disponibilidad>
						<precio>7630</precio>
						<claseComercial/>
					</tarifas>
					<tarifas>
						<cdgoTarifa>GL115</cdgoTarifa>
						<descTarifa>IDA Y VUELTA</descTarifa>
						<disponibilidad>Si</disponibilidad>
						<precio>7630</precio>
						<claseComercial/>
					</tarifas>
					<tarifas>
						<cdgoTarifa>GL010</cdgoTarifa>
						<descTarifa>FLEXIBLE</descTarifa>
						<disponibilidad>Si</disponibilidad>
						<precio>9540</precio>
						<claseComercial/>
					</tarifas>
				</ocupaciones>
			</clases>
			<clases>
				<cdgoClase>C</cdgoClase>
				<descClase>Preferente</descClase>
				<ocupaciones>
					<cdgoOcupacion>CR</cdgoOcupacion>
					<descOcupacion>Sentada</descOcupacion>
					<tarifas>
						<descTarifa>Nino</descTarifa>
						<disponibilidad>Si</disponibilidad>
						<precio>8040</precio>
						<claseComercial/>
					</tarifas>
					<tarifas>
						<cdgoTarifa>GL013</cdgoTarifa>
						<descTarifa>Tfa. Tarjeta Dorada</descTarifa>
						<disponibilidad>Si</disponibilidad>
						<precio>8040</precio>
						<claseComercial/>
					</tarifas>
					<tarifas>
						<cdgoTarifa>GL030</cdgoTarifa>
						<descTarifa>C. Joven &lt; 26</descTarifa>
						<disponibilidad>Si</disponibilidad>
						<precio>10720</precio>
						<claseComercial/>
					</tarifas>
					<tarifas>
						<cdgoTarifa>GL115</cdgoTarifa>
						<descTarifa>IDA Y VUELTA</descTarifa>
						<disponibilidad>Si</disponibilidad>
						<precio>10720</precio>
						<claseComercial/>
					</tarifas>
					<tarifas>
						<cdgoTarifa>GL010</cdgoTarifa>
						<descTarifa>FLEXIBLE</descTarifa>
						<disponibilidad>Si</disponibilidad>
						<precio>13400</precio>
						<claseComercial/>
					</tarifas>
				</ocupaciones>
			</clases>
		</infoTrenIda>
		<infoTrenIda>
			<tren>02073</tren>
			<tipoTren>
				<cdgoTipoTren>006</cdgoTipoTren>
				<descTipoTren>AVE</descTipoTren>
			</tipoTren>
			<horaSalida>0710</horaSalida>
			<horaLlegada>0935</horaLlegada>
			<origen>
				<cdgoEstacion>54413</cdgoEstacion>
				<descEstacion>MALAGA M.Z</descEstacion>
			</origen>
			<destino>
				<cdgoEstacion>60000</cdgoEstacion>
				<descEstacion>MADRID-P.A</descEstacion>
			</destino>
			<clases>
				<cdgoClase>T</cdgoClase>
				<descClase>Turista</descClase>
				<ocupaciones>
					<cdgoOcupacion>CR</cdgoOcupacion>
					<descOcupacion>Sentada</descOcupacion>
					<tarifas>
						<cdgoTarifa>GL011</cdgoTarifa>
						<descTarifa>Nino</descTarifa>
						<disponibilidad>Si</disponibilidad>
						<precio>4770</precio>
						<claseComercial/>
					</tarifas>
					<tarifas>
						<cdgoTarifa>GL013</cdgoTarifa>
						<descTarifa>Tfa. Tarjeta Dorada</descTarifa>
						<disponibilidad>Si</disponibilidad>
						<precio>4770</precio>
						<claseComercial/>
					</tarifas>
					<tarifas>
						<cdgoTarifa>GL030</cdgoTarifa>
						<descTarifa>C. Joven &lt; 26</descTarifa>
						<disponibilidad>Si</disponibilidad>
						<precio>6360</precio>
						<claseComercial/>
					</tarifas>
					<tarifas>
						<cdgoTarifa>GL115</cdgoTarifa>
						<descTarifa>IDA Y VUELTA</descTarifa>
						<disponibilidad>Si</disponibilidad>
						<precio>6360</precio>
						<claseComercial/>
					</tarifas>
					<tarifas>
						<cdgoTarifa>GL010</cdgoTarifa>
						<descTarifa>FLEXIBLE</descTarifa>
						<disponibilidad>Si</disponibilidad>
						<precio>7950</precio>
						<claseComercial/>
					</tarifas>
				</ocupaciones>
			</clases>
			<clases>
				<cdgoClase>P</cdgoClase>
				<descClase>Turista Plus</descClase>
				<ocupaciones>
					<cdgoOcupacion>CR</cdgoOcupacion>
					<descOcupacion>Sentada</descOcupacion>
					<tarifas>
						<cdgoTarifa>GL011</cdgoTarifa>
						<descTarifa>Nino</descTarifa>
						<disponibilidad>Si</disponibilidad>
						<precio>5725</precio>
						<claseComercial/>
					</tarifas>
					<tarifas>
						<cdgoTarifa>GL013</cdgoTarifa>
						<descTarifa>Tfa. Tarjeta Dorada</descTarifa>
						<disponibilidad>Si</disponibilidad>
						<precio>5725</precio>
						<claseComercial/>
					</tarifas>
					<tarifas>
						<cdgoTarifa>GL030</cdgoTarifa>
						<descTarifa>C. Joven &lt; 26</descTarifa>
						<disponibilidad>Si</disponibilidad>
						<precio>7630</precio>
						<claseComercial/>
					</tarifas>
					<tarifas>
						<cdgoTarifa>GL115</cdgoTarifa>
						<descTarifa>IDA Y VUELTA</descTarifa>
						<disponibilidad>Si</disponibilidad>
						<precio>7630</precio>
						<claseComercial/>
					</tarifas>
					<tarifas>
						<cdgoTarifa>GL010</cdgoTarifa>
						<descTarifa>FLEXIBLE</descTarifa>
						<disponibilidad>Si</disponibilidad>
						<precio>9540</precio>
						<claseComercial/>
					</tarifas>
				</ocupaciones>
			</clases>
			<clases>
				<cdgoClase>C</cdgoClase>
				<descClase>Preferente</descClase>
				<ocupaciones>
					<cdgoOcupacion>CR</cdgoOcupacion>
					<descOcupacion>Sentada</descOcupacion>
					<tarifas>
						<cdgoTarifa>GL011</cdgoTarifa>
						<descTarifa>Nino</descTarifa>
						<disponibilidad>Si</disponibilidad>
						<precio>8040</precio>
						<claseComercial/>
					</tarifas>
					<tarifas>
						<cdgoTarifa>GL013</cdgoTarifa>
						<descTarifa>Tfa. Tarjeta Dorada</descTarifa>
						<disponibilidad>Si</disponibilidad>
						<precio>8040</precio>
						<claseComercial/>
					</tarifas>
					<tarifas>
						<cdgoTarifa>GL030</cdgoTarifa>
						<descTarifa>C. Joven &lt; 26</descTarifa>
						<disponibilidad>Si</disponibilidad>
						<precio>10720</precio>
						<claseComercial/>
					</tarifas>
					<tarifas>
						<cdgoTarifa>GL115</cdgoTarifa>
						<descTarifa>IDA Y VUELTA</descTarifa>
						<disponibilidad>Si</disponibilidad>
						<precio>10720</precio>
						<claseComercial/>
					</tarifas>
					<tarifas>
						<cdgoTarifa>GL010</cdgoTarifa>
						<descTarifa>FLEXIBLE</descTarifa>
						<disponibilidad>Si</disponibilidad>
						<precio>13400</precio>
						<claseComercial/>
					</tarifas>
				</ocupaciones>
			</clases>
		</infoTrenIda>
		<infoTrenIda>
			<tren>02083</tren>
			<tipoTren>
				<cdgoTipoTren>004</cdgoTipoTren>
				<descTipoTren>AVE</descTipoTren>
			</tipoTren>
			<horaSalida>0800</horaSalida>
			<horaLlegada>1040</horaLlegada>
			<origen>
				<cdgoEstacion>54413</cdgoEstacion>
				<descEstacion>MALAGA M.Z</descEstacion>
			</origen>
			<destino>
				<cdgoEstacion>60000</cdgoEstacion>
				<descEstacion>MADRID-P.A</descEstacion>
			</destino>
			<clases>
				<cdgoClase>T</cdgoClase>
				<descClase>Turista</descClase>
				<ocupaciones>
					<cdgoOcupacion>CR</cdgoOcupacion>
					<descOcupacion>Sentada</descOcupacion>
					<tarifas>
						<cdgoTarifa>GL011</cdgoTarifa>
						<descTarifa>Nino</descTarifa>
						<disponibilidad>Si</disponibilidad>
						<precio>4770</precio>
						<claseComercial/>
					</tarifas>
					<tarifas>
						<cdgoTarifa>GL013</cdgoTarifa>
						<descTarifa>Tfa. Tarjeta Dorada</descTarifa>
						<disponibilidad>Si</disponibilidad>
						<precio>4770</precio>
						<claseComercial/>
					</tarifas>
					<tarifas>
						<cdgoTarifa>GL030</cdgoTarifa>
						<descTarifa>C. Joven &lt; 26</descTarifa>
						<disponibilidad>Si</disponibilidad>
						<precio>6360</precio>
						<claseComercial/>
					</tarifas>
					<tarifas>
