=== Koko2034/lm/EjerciciosClaseLM/xml/menu.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--DTD generated by XMLSpy v2011 rel. 2 (http://www.altova.com)-->
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT calorias (#PCDATA)>
<!ELEMENT forma (#PCDATA)>
<!ELEMENT comida ((nombre, precio, descripcion, calorias, forma+))>
<!ATTLIST comida id CDATA #REQUIRED>
<!ELEMENT MENU ((comida+))>

=== Koko2034/lm/EjerciciosClaseLM/xml/menuError.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE MENU SYSTEM "menu.dtd">
<MENU>
	<comida id="01">
		<nombre><![CDATA[Café]]></nombre>
		<precio>2.60</precio>
		<descripcion><![CDATA[Café de cualquier clase]]></descripcion>
		<calorias>650</calorias>
		<forma>liquido</forma>
	</comida>
	<comida id="'02">
		<nombre>Tortilla</nombre>
		<precio>10.00</precio>
		<descripcion>Tortilla francesa</descripcion>
		<calorias>809</calorias>
		<forma>solido</forma>
	</comida>
	<comida id="03">
		<nombre>Cereales</nombre>
		<precio>3.50</precio>
		<descripcion>Cereales de chocolate con leche</descripcion>
		<calorias>450</calorias>
		<forma>solido</forma>
		<forma>solido</forma>
	</comida>
	<comida id="04">
		<nombre>Tostadas</nombre>
		<precio>2.00</precio>
		<descripcion>Tostadas con mantequilla</descripcion>
		<calorias>900</calorias>
		<forma>solido</forma>
	</comida>
	<comida id="05">
		<nombre>Tortitas</nombre>
		<precio>5.00</precio>
		<descripcion>Tortitas con nata</descripcion>
		<calorias>1500</calorias>
		<forma>solido</forma>
		<forma>elaborado</forma>
	</comida>
	<comida id="06">
		<nombre>Espaguetis</nombre>
		<precio>12.00</precio>
		<descripcion>Espaguetis con tomate casero</descripcion>
		<calorias>650</calorias>
		<forma>solido</forma>
		<forma>elaborado</forma>
	</comida>
	<comida id="07">
		<nombre><![CDATA[Albóndigas]]></nombre>
		<precio></precio>
		<descripcion><![CDATA[Albóndigas con salsa]]></descripcion>
		<calorias>809</calorias>
		<forma>solido</forma>
		<forma>muy elaborado</forma>
	</comida>
	<comida id="08">
		<nombre>Puchero</nombre>
		<precio>2.00</precio>
		<descripcion>Puchero casero</descripcion>
		<calorias>450</calorias>
		<forma>solido</forma>
		<forma>elaborado</forma>
	</comida>
	<comida id="09">
		<nombre><![CDATA[Lasaña]]></nombre>
		<precio>20.00</precio>
		<descripcion><![CDATA[Lasaña de carne]]></descripcion>
		<calorias>900</calorias>
		<forma>solido</forma>
		<forma>muy elaborado</forma>
	</comida>
	<comida id="10">
		<nombre>Hamburguesa</nombre>
		<precio>8.00</precio>
		<descripcion><![CDATA[Hamburguesa común]]></descripcion>
		<calorias>1500</calorias>
		<forma>solido</forma>
		<forma>elaborado</forma>
	</comida>
	<comida id="11">
		<nombre>Leche</nombre>
		<precio>1.00</precio>
		<descripcion>Vaso de leche</descripcion>
		<calorias>650</calorias>
		<forma>liquido</forma>
	</comida>
	<comida id="12">
		<nombre>Tortilla con pimientos</nombre>
		<precio>10.00</precio>
		<descripcion>Tortilla francesa</descripcion>
		<calorias>809</calorias>
		<forma>solido</forma>
		<forma>elaborado</forma>
	</comida>
	<comida id="13">
		<nombre>Bocadillos</nombre>
		<precio>3.50</precio>
		<descripcion>Bocadillos de cualquier forma</descripcion>
		<calorias>780</calorias>
		<forma>solido</forma>
		<forma>elaborado</forma>
	</comida>
	<comida id="14">
		<nombre>Hot Dogs</nombre>
		<precio>2.00</precio>
		<descripcion>Hot Dogs con salsa</descripcion>
		<calorias>1300</calorias>
		<forma>solido</forma>
		<forma>elaborado</forma>
	</comida>
	<comida id="15">
		<nombre>Pizza</nombre>
		<precio>7.00</precio>
		<descripcion>Pizza de cualquier forma</descripcion>
		<calorias>1500</calorias>
		<forma>solido</forma>
		<forma>muy elaborado</forma>
	</comida>
</MENU>
