=== Koko2034/lm/EjerciciosClaseLM/xml/productosValidador.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2011 rel. 2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="productos">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="producto" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
		<!--  No se puede repetir el codigo  -->
		<xs:unique name="unique-codigo">
			<xs:selector xpath="producto"/>
			<xs:field xpath="@codigo"/>
		</xs:unique>
	</xs:element>
	<xs:element name="producto">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre"/>
				<xs:element ref="descripcion"/>
				<xs:element ref="precio"/>
				<xs:element ref="stock"/>
			</xs:sequence>
			<xs:attribute name="codigo" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:pattern value="([0-9])*"/>
						<!-- los codigos solo pueden ser numeros enteros del 0 al 9, el asterisco es para que se pueda poner más de un digito-->
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="categoria" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="monitor"/>
						<xs:enumeration value="portatil"/>
						<!-- solo se puede crear dos categorias y es obligatorio -->
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="30"/>
			</xs:restriction>
			<!-- se puede introducir como maximo 30 caracteres -->
		</xs:simpleType>
	</xs:element>
	<xs:element name="descripcion">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="200"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="precio">
		<xs:simpleType>
			<xs:restriction base="xs:decimal">
				<xs:minInclusive value="1"/>
				<xs:maxInclusive value="1000"/>
			</xs:restriction>
			<!-- los precios van de 1 a 1000 en decimal -->
		</xs:simpleType>
	</xs:element>
	<xs:element name="stock">
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="1"/>
				<xs:maxInclusive value="200"/>
			</xs:restriction>
			<!-- Números enteros del 1 al 200" -->
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== Koko2034/lm/EjerciciosClaseLM/xml/productos.xml
<?xml version="1.0" encoding="UTF-8"?>
<productos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="productosValidador.xsd">
	<producto codigo="0" categoria="portatil">
		<nombre>HP Stream 11r000n</nombre>
		<descripcion> Portátil de 11.6" HD (Intel Celeron N3050, 2 GB de RAM, disco de 32 GB eMMC + 100 GB One Drive, Windows 10 x64</descripcion>
		<precio>189</precio>
		<stock>49</stock>
	</producto>
	<producto codigo="1" categoria="portatil">
		<nombre>Lenovo Z51-70</nombre>
		<descripcion> Lenovo Z51-70 - Portátil de 15.6 " Full HD (Intel i5-5200U, 12 GB de RAM, 1 TB de disco duro, gráfica AMD R9 M375 4 GB, Windows 8.1) plata - Teclado QWERTY Español</descripcion>
		<precio>600</precio>
		<stock>5</stock>
	</producto>
	<producto codigo="2" categoria="portatil">
		<nombre>ASUS K541UV-XX335T</nombre>
		<descripcion> Ordenador portátil de 15.6" HD (Intel Core i7-6500U, 4 GB de RAM, HDD de 1 TB, NVIDIA GeForce GT920M 2 GB, Windows 10 Original), negro chocolate - Teclado QWERTY Español</descripcion>
		<precio>549</precio>
		<stock>12</stock>
	</producto>
	<producto codigo="3" categoria="monitor">
		<nombre>LG 22M47VQ-P</nombre>
		<descripcion> Monitor LED de 21.5" (16:9, 1920 x 1080 pixeles, triple conectividad, división de pantalla en 4), color negro</descripcion>
		<precio>109</precio>
		<stock>9</stock>
	</producto>
	<producto codigo="4" categoria="monitor">
		<nombre>Dell UltraSharp U2414H</nombre>
		<descripcion>Monitor LED de 23.8" (1920 x 1080p, 250 cd/m2, IPS, 8 ms, HDMI, DisplayPort) color negro y plateado</descripcion>
		<precio>240</precio>
		<stock>11</stock>
	</producto>
	<producto codigo="5" categoria="monitor">
		<nombre>Samsung C27F390FHU </nombre>
		<descripcion>Full HD VA Negro - Monitor (1920 x 1080 Pixeles, LCD, Full HD, VA, 1280 x 720 (HD 720), 1920 x 1080 (HD 1080), 3000:1)</descripcion>
		<precio>245</precio>
		<stock>1</stock>
	</producto>
</productos>
