=== Koko2034/lm/EjerciciosClaseLM/xml/Schema-coches.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2011 rel. 2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="coches">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="coche" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="marca" type="xs:string"/>
							<xs:element name="nombremodelo" type="xs:string"/>
							<xs:element name="precio" type="TipoPrecio"/>
							<xs:element name="imagen" type="xs:string"/>
						</xs:sequence>
						<xs:attribute name="matricula" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:pattern value="[A-Z]{2}(-[0-9]{5})"/>
									<xs:pattern value="[A-Z]{2}(-[0-9]{4})(-[A-Z]{1,2})"/>
									<xs:pattern value="[0-9]{4}(-[B-Z-[AEIOUQ]]{3})"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="PrimaryKey">
			<xs:selector xpath="coche"/>
			<xs:field xpath="@matricula"/>
		</xs:unique>
	</xs:element>
	<xs:simpleType name="TipoPrecio">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="0"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== Koko2034/lm/EjerciciosClaseLM/xml/Coches.xml
<?xml version="1.0" encoding="UTF-8"?>
<coches xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Schema-coches.xsd">
	<coche matricula="MA-98685">
		<marca>Seat</marca>
		<nombremodelo>Supermirafiori</nombremodelo>
		<precio>12165.50</precio>
		<imagen/>
	</coche>
	<coche matricula="MA-2345-AS">
		<marca>Seat</marca>
		<nombremodelo>Seat Ibiza</nombremodelo>
		<precio>8557.9</precio>
		<imagen/>
	</coche>
	<coche matricula="1200-BSF">
		<marca>Ferrari</marca>
		<nombremodelo>TestaRossa</nombremodelo>
		<precio>330000</precio>
		<imagen/>
	</coche>
</coches>
