=== Koko2034/lm/EjerciciosClaseLM/xml/validadorContactos.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:contactos="http://www.example.com/contactos" targetNamespace="http://www.example.com/contactos" elementFormDefault="qualified">
	<element name="contactos">
		<complexType>
			<sequence>
				<element name="contacto" minOccurs="0" maxOccurs="unbounded">
					<complexType>
						<sequence>
							<element name="persona" type="contactos:TipoPersona"/>
							<element name="localización" type="contactos:TipoLocalización"/>
							<element name="teléfono" type="string"/>
							<element name="descripción" type="contactos:TipoDescripción"/>
						</sequence>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
	<complexType name="TipoPersona">
		<group ref="contactos:GrupoPersona"/>
		<attribute name="idioma" default="ES"/>
		<attribute name="edad" use="required">
			<simpleType>
				<restriction base="integer">
					<minInclusive value="1"/>
					<maxInclusive value="140"/>
				</restriction>
			</simpleType>
		</attribute>
	</complexType>
	<group name="GrupoPersona">
		<sequence>
			<element name="nombre" type="string" minOccurs="1" maxOccurs="unbounded"/>
			<element name="apellido1" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="apellido2" type="string" minOccurs="0" maxOccurs="1"/>
		</sequence>
	</group>
	<complexType name="TipoLocalización">
		<choice minOccurs="0" maxOccurs="unbounded">
			<element name="dirección" type="string"/>
			<sequence>
				<element name="latitud" type="string" minOccurs="0" maxOccurs="1"/>
				<element name="longitud" type="string" minOccurs="0" maxOccurs="1"/>
			</sequence>
		</choice>
	</complexType>
	<complexType name="TipoDescripción" mixed="true">
		<choice minOccurs="0" maxOccurs="unbounded">
			<element name="em" type="string"/>
			<element name="strong" type="string"/>
			<element name="br" type="string"/>
		</choice>
	</complexType>
</schema>

=== Koko2034/lm/EjerciciosClaseLM/xml/contactos.xml
<?xml version="1.0"?>
<contactos xsi:schemaLocation="http://www.example.com/contactos validadorContactos.xsd" xmlns="http://www.example.com/contactos" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<contacto>
		<persona idioma="ES" edad="20"> 
			<nombre>José</nombre>
			<apellido1>Pérez</apellido1>
			<apellido2>García</apellido2>
		</persona>
		<localización>
			<dirección>Ciudad Intermedia, España</dirección>
			<latitud>34.031892</latitud>
			<longitud>3.207642</longitud>
		</localización>
		<teléfono>955-123-456</teléfono>
		<descripción>José es el director de <em>una sucursal</em>.<br/>José es <strong> buena persona </strong>
		</descripción>
	</contacto>
	<contacto>
		<persona idioma="EN" edad="19">
			<nombre>Antonio</nombre>
			<apellido1>Pérez</apellido1>
			<apellido2>Gutiérrez</apellido2>
		</persona>
		<localización>
			<dirección>Mordor, España</dirección>
		</localización>
		<teléfono>956-654-321</teléfono>
		<descripción>Antonio es el apoderado de <em>una sucursal</em>.<br/> A Antonio <strong> le gusta su trabajo </strong>
		</descripción>
	</contacto>
		<contacto>
		<persona idioma="IT" edad="39">
			<nombre>Luis</nombre>
			<apellido1>Pérez</apellido1>
		</persona>
		<localización>
			<dirección>Insula Barataria, España</dirección>
		</localización>
		<teléfono>921-654-459</teléfono>
		<descripción>Antonio es el apoderado de <em>una sucursal</em>.<br/> A Antonio <strong> le gusta su trabajo </strong>
		</descripción>
	</contacto>
</contactos>
